# Generated by Django 6.0.6 on 2026-06-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='alternate_google_banner_ad',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alternate_google_banner_link',
            field=models.URLField(blank=True),
        ),
    ]
