# Generated by Django 6.0.6 on 2026-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_alternate_google_banner_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_adsense_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_ad_type',
            field=models.CharField(choices=[('custom', 'Custom Image Ad'), ('google', 'Google AdSense Ad')], default='custom', max_length=20),
        ),
    ]
