# Generated by Django 6.0.6 on 2026-06-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_google_adsense_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='google_adsense_code',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_adsense_publisher_id',
            field=models.CharField(blank=True, help_text='Example: ca-pub-1234567890123456', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_adsense_slot_id',
            field=models.CharField(blank=True, help_text='Example: 1234567890', max_length=100),
        ),
    ]
