# Generated by Django 6.0.6 on 2026-06-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sitesettings_google_adsense_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='car_detail_sidebar_google_ad_active',
            field=models.BooleanField(default=False, help_text='Turn on Google AdSense sidebar ad on car detail page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='car_detail_sidebar_google_slot_id',
            field=models.CharField(blank=True, help_text='Car detail sidebar slot ID. Example: 1234567890', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_adsense_slot_id',
            field=models.CharField(blank=True, help_text='Homepage banner slot ID. Example: 1234567890', max_length=100),
        ),
    ]
