# Generated by Django 6.0.6 on 2026-07-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_car_detail_sidebar_google_ad_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_cancelled_message',
            field=models.TextField(blank=True, default='Payment was cancelled. You have not been charged.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_success_message',
            field=models.TextField(blank=True, default='Payment successful. Your dealer package is now active.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable Stripe payments.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_mode',
            field=models.CharField(choices=[('test', 'Test Mode'), ('live', 'Live Mode')], default='test', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_price_enterprise',
            field=models.CharField(blank=True, help_text='Stripe Price ID for Enterprise package.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_price_premium',
            field=models.CharField(blank=True, help_text='Stripe Price ID for Premium package.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_price_professional',
            field=models.CharField(blank=True, help_text='Stripe Price ID for Professional package.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_price_starter',
            field=models.CharField(blank=True, help_text='Stripe Price ID for Starter package.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='car_detail_sidebar_google_ad_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='car_detail_sidebar_google_slot_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_adsense_slot_id',
            field=models.CharField(blank=True, help_text='Homepage banner slot ID.', max_length=100),
        ),
    ]
