# Generated by Django 6.0.6 on 2026-07-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_payment_cancelled_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, help_text='Stripe publishable key. Example: pk_test_... or pk_live_...', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, help_text='Stripe secret key. Example: sk_test_... or sk_live_...', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, help_text='Stripe webhook secret. Example: whsec_...', max_length=255),
        ),
    ]
