# Generated by Django 6.0.6 on 2026-07-11 05:38

import django.core.validators
import django.db.models.deletion
import rentals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('ute', 'Ute'), ('wagon', 'Wagon'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('van', 'Van'), ('people_mover', 'People Mover'), ('other', 'Other')], max_length=30)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG'), ('other', 'Other')], max_length=20)),
                ('seats', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=20)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weekly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_rental_days', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unlimited_kilometres', models.BooleanField(default=False)),
                ('daily_kilometre_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('rental_conditions', models.TextField(blank=True)),
                ('pickup_address', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('ACT', 'Australian Capital Territory'), ('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], max_length=3)),
                ('postcode', models.CharField(max_length=4)),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(max_length=30)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Car',
                'verbose_name_plural': 'Rental Cars',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rentals.models.rental_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.rentalcar')),
            ],
            options={
                'verbose_name': 'Rental Car Image',
                'verbose_name_plural': 'Rental Car Images',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rentalcar',
            index=models.Index(fields=['moderation_status', 'is_active', 'is_available'], name='rentals_ren_moderat_004269_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcar',
            index=models.Index(fields=['state', 'suburb'], name='rentals_ren_state_ea9489_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcar',
            index=models.Index(fields=['make', 'model'], name='rentals_ren_make_706e27_idx'),
        ),
    ]
