# Generated by Django 6.0.6 on 2026-07-16 17:50

import django.db.models.deletion
import rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('owner_notified', models.BooleanField(default=False)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rental Enquiry',
                'verbose_name_plural': 'Rental Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='rentalcarimage',
            name='image',
            field=models.ImageField(upload_to=rentals.models.rental_image_upload_path, validators=[rentals.models.validate_rental_image_size]),
        ),
        migrations.AlterField(
            model_name='rentalcarimage',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='rentalcarimage',
            constraint=models.UniqueConstraint(fields=('rental',), name='one_image_per_rental'),
        ),
        migrations.AddField(
            model_name='rentalenquiry',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='rentals.rentalcar'),
        ),
        migrations.AddIndex(
            model_name='rentalenquiry',
            index=models.Index(fields=['rental', 'status', 'created_at'], name='rentals_ren_rental__57a09c_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalenquiry',
            index=models.Index(fields=['customer_email', 'created_at'], name='rentals_ren_custome_01c31b_idx'),
        ),
    ]
