# Generated by Django 6.0.6 on 2026-07-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('short_description', models.CharField(blank=True, max_length=220)),
                ('body_type', models.CharField(choices=[('all', 'All'), ('suv', 'SUV'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon'), ('ute', 'Ute'), ('van', 'Van'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('4wd', '4WD'), ('ev', 'Electric Vehicle'), ('hybrid', 'Hybrid')], default='all', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='amazon_affiliate/products/')),
                ('amazon_affiliate_url', models.URLField()),
                ('button_text', models.CharField(default='View on Amazon', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amazon Product',
                'verbose_name_plural': 'Amazon Products',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
