# Generated by Django 6.0.6 on 2026-07-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='amazon_product_url',
            field=models.URLField(blank=True, help_text='Paste normal Amazon product URL here.'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='asin',
            field=models.CharField(blank=True, help_text='Amazon product ASIN. Useful for future API sync.', max_length=30),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('dash_cam', 'Dash Cam'), ('phone_holder', 'Phone Holder'), ('tyre_inflator', 'Tyre Inflator'), ('car_vacuum', 'Car Vacuum'), ('jump_starter', 'Jump Starter'), ('roof_rack', 'Roof Rack'), ('floor_mats', 'Floor Mats'), ('seat_covers', 'Seat Covers'), ('boot_organiser', 'Boot Organiser'), ('recovery_gear', 'Recovery Gear'), ('ev_accessory', 'EV Accessory')], default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='amazon_affiliate_url',
            field=models.URLField(blank=True, help_text='Paste your affiliate URL here. Example: ?tag=mycarmarketau-22'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='short_description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='title',
            field=models.CharField(max_length=180),
        ),
    ]
