# Generated by Django 6.0.6 on 2026-07-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_affiliate', '0002_amazonproduct_amazon_product_url_amazonproduct_asin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAffiliateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(default='mycarmarketau-22', help_text='Your Amazon Associates Store ID / Tracking ID.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amazon Affiliate Setting',
                'verbose_name_plural': 'Amazon Affiliate Settings',
            },
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='amazon_affiliate_url',
            field=models.URLField(blank=True, help_text='Auto generated using your Store ID, but editable.'),
        ),
    ]
