# Generated by Django 6.0.6 on 2026-07-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_affiliate', '0003_amazonaffiliatesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=220)),
                ('image', models.ImageField(blank=True, null=True, upload_to='amazon_affiliate/categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Amazon Category',
                'verbose_name_plural': 'Amazon Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='asin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='category',
            field=models.CharField(blank=True, default='general', help_text='Old category field. Kept for migration safety.', max_length=40),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='title',
            field=models.CharField(blank=True, default='Amazon Car Accessory', max_length=180),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='amazon_affiliate.amazoncategory'),
        ),
    ]
