# Generated by Django 6.0.6 on 2026-07-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_affiliate', '0004_amazoncategory_alter_amazonproduct_asin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='amazonproduct',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='amazonaffiliatesettings',
            name='store_id',
            field=models.CharField(default='mycarmarket-22', help_text='Your Amazon Associates Store ID / Tracking ID. Example: mycarmarket-22', max_length=100),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='amazon_affiliate_url',
            field=models.URLField(blank=True, editable=False, help_text='Auto-generated affiliate URL.'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='amazon_product_url',
            field=models.URLField(blank=True, help_text='Paste normal Amazon product URL here. Store ID will be added automatically.'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='asin',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
    ]
