# Generated by Django 6.0.6 on 2026-07-15 12:44

import django.core.validators
import django.db.models.deletion
import services.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mechanic', 'Mechanic'), ('driving_lessons', 'Driving Lessons'), ('car_detailing', 'Car Detailing'), ('car_wash', 'Car Wash'), ('tyres_wheels', 'Tyres & Wheels'), ('battery_service', 'Battery Service'), ('auto_electrician', 'Auto Electrician'), ('roadworthy_inspection', 'Roadworthy Inspection'), ('car_inspection', 'Car Inspection'), ('towing', 'Towing'), ('panel_beating_paint', 'Panel Beating & Paint'), ('windscreen_repair', 'Windscreen Repair'), ('accessories_installation', 'Car Accessories Installation'), ('vehicle_transport', 'Vehicle Transport'), ('other', 'Other Car Services')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('ACT', 'Australian Capital Territory'), ('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], db_index=True, max_length=3)),
                ('suburb', models.CharField(db_index=True, max_length=100)),
                ('postcode', models.CharField(max_length=4)),
                ('service_area', models.CharField(blank=True, max_length=255)),
                ('mobile_service', models.BooleanField(db_index=True, default=False)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('website', models.URLField(blank=True)),
                ('provider_name', models.CharField(max_length=150)),
                ('provider_email', models.EmailField(max_length=254)),
                ('provider_phone', models.CharField(max_length=30)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_service_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Service',
                'verbose_name_plural': 'Car Services',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=services.models.service_image_upload_path, validators=[services.models.validate_service_image_size])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.carservice')),
            ],
            options={
                'verbose_name': 'Car Service Image',
                'verbose_name_plural': 'Car Service Images',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('provider_notified', models.BooleanField(default=False)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='services.carservice')),
            ],
            options={
                'verbose_name': 'Service Enquiry',
                'verbose_name_plural': 'Service Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='carservice',
            index=models.Index(fields=['moderation_status', 'is_active'], name='services_ca_moderat_74d556_idx'),
        ),
        migrations.AddIndex(
            model_name='carservice',
            index=models.Index(fields=['category', 'state'], name='services_ca_categor_066836_idx'),
        ),
        migrations.AddIndex(
            model_name='carservice',
            index=models.Index(fields=['state', 'suburb'], name='services_ca_state_fb47bd_idx'),
        ),
        migrations.AddIndex(
            model_name='carservice',
            index=models.Index(fields=['mobile_service', 'is_active'], name='services_ca_mobile__41fd6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='carserviceimage',
            constraint=models.UniqueConstraint(fields=('service',), name='one_image_per_car_service'),
        ),
        migrations.AddIndex(
            model_name='serviceenquiry',
            index=models.Index(fields=['service', 'status', 'created_at'], name='services_se_service_28c54b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceenquiry',
            index=models.Index(fields=['customer_email', 'created_at'], name='services_se_custome_2e8810_idx'),
        ),
    ]
