# Generated by Django 6.0.6 on 2026-07-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='category',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('driving_lessons', 'Driving Lessons'), ('car_detailing', 'Car Detailing'), ('car_wash', 'Car Wash'), ('tyres_wheels', 'Tyres & Wheels'), ('battery_service', 'Battery Service'), ('auto_electrician', 'Auto Electrician'), ('roadworthy_inspection', 'Roadworthy Inspection'), ('car_inspection', 'Car Inspection'), ('towing', 'Towing'), ('panel_beating_paint', 'Panel Beating & Paint'), ('windscreen_repair', 'Windscreen Repair'), ('window_tinting', 'Window Tinting'), ('accessories_installation', 'Car Accessories Installation'), ('vehicle_transport', 'Vehicle Transport'), ('other', 'Other Car Services')], db_index=True, max_length=50),
        ),
    ]
