# Generated by Django 6.0.6 on 2026-07-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_carservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='category',
            field=models.CharField(choices=[('car_service', 'Car Service'), ('logbook_servicing', 'Logbook Servicing'), ('mechanic', 'Mechanic'), ('car_detailing', 'Car Detailing'), ('car_wash', 'Car Wash'), ('tyres_wheels', 'Tyres & Wheels'), ('battery_service', 'Battery Service'), ('auto_electrician', 'Auto Electrician'), ('roadworthy_inspection', 'Roadworthy Inspection'), ('car_inspection', 'Car Inspection'), ('towing', 'Towing'), ('panel_beating_paint', 'Panel Beating & Paint'), ('windscreen_repair', 'Windscreen Repair'), ('headlight_restoration', 'Headlight Restoration'), ('window_tinting', 'Window Tinting'), ('air_conditioning_service', 'Air Conditioning Service'), ('brake_clutch_repairs', 'Brake & Clutch Repairs'), ('suspension_steering', 'Suspension & Steering'), ('car_audio_multimedia', 'Car Audio & Multimedia'), ('dash_cam_installation', 'Dash Cam Installation'), ('accessories_installation', 'Car Accessories Installation'), ('vehicle_transport', 'Vehicle Transport'), ('driving_lessons', 'Driving Lessons'), ('ev_service', 'EV (Electric Vehicle) Service'), ('other', 'Other Car Services')], db_index=True, max_length=50),
        ),
    ]
