# Generated by Django 6.0.6 on 2026-07-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('make', models.CharField(help_text='Example: Toyota, Ford, Mazda', max_length=100)),
                ('model', models.CharField(help_text='Example: Corolla, Ranger, CX-5', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Optional. Example: 2023', null=True)),
                ('body_type', models.CharField(blank=True, help_text='Example: SUV, Sedan, Hatchback, Ute', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=8.0, help_text='Example: 8.5', max_digits=3)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('summary', models.TextField(help_text='Short SEO-friendly intro / quick verdict.')),
                ('pros', models.TextField(blank=True, help_text='One point per line.')),
                ('cons', models.TextField(blank=True, help_text='One point per line.')),
                ('content', models.TextField(help_text='Full review article content.')),
                ('faq', models.TextField(blank=True, help_text='Optional FAQ content. Add question and answer format.')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car Review',
                'verbose_name_plural': 'Car Reviews',
                'ordering': ['-published_at'],
            },
        ),
    ]
