# Generated by Django 6.0.6 on 2026-07-07 14:02

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreview',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.review_image_upload_path),
        ),
    ]
