# Generated by Django 6.0.6 on 2026-06-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_car_image_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('VIC', 'Victoria'), ('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], default='VIC', max_length=3),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, help_text='Example: Melbourne, Sydney, Brisbane', max_length=150),
        ),
    ]
