# Generated by Django 6.0.6 on 2026-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_car_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.CharField(blank=True, choices=[('VIC', 'Victoria'), ('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
