# Generated by Django 6.0.6 on 2026-06-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_car_state_car_suburb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
    ]
