# Generated by Django 6.0.6 on 2026-06-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_remove_car_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
