# Generated by Django 6.0.6 on 2026-06-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_car_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
