# Generated by Django 6.0.6 on 2026-06-09 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_favouritecar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('package', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter - $99 AUD'), ('professional', 'Professional - $299 AUD'), ('premium', 'Premium - $599 AUD'), ('enterprise', 'Enterprise - $999 AUD')], default='free', max_length=20)),
                ('is_dealer', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('package_active', models.BooleanField(default=True)),
                ('max_listings', models.PositiveIntegerField(default=3)),
                ('featured_ads_allowed', models.PositiveIntegerField(default=0)),
                ('priority_support', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
