# Generated by Django 6.0.6 on 2026-06-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_dealerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_banners/'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='is_featured_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_logos/'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
