# Generated by Django 6.0.6 on 2026-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_dealerprofile_address_dealerprofile_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
