# Generated by Django 6.0.6 on 2026-06-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_dealersubscription_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='package_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
