# Generated by Django 6.0.6 on 2026-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_dealerprofile_package_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
