# Generated by Django 6.0.6 on 2026-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_alter_enquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='banner_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=20),
        ),
    ]
