# Generated by Django 6.0.6 on 2026-06-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_dealerprofile_banner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='abn',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='extended_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='finance_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='test_drive_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='trade_in_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
