# Generated by Django 6.0.6 on 2026-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_dealerprofile_abn_dealerprofile_delivery_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='friday_hours',
            field=models.CharField(blank=True, default='9:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='monday_hours',
            field=models.CharField(blank=True, default='9:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='open_24_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='saturday_hours',
            field=models.CharField(blank=True, default='Closed', max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='sunday_hours',
            field=models.CharField(blank=True, default='Closed', max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='thursday_hours',
            field=models.CharField(blank=True, default='9:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='tuesday_hours',
            field=models.CharField(blank=True, default='9:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='wednesday_hours',
            field=models.CharField(blank=True, default='9:00 AM - 5:00 PM', max_length=100),
        ),
    ]
