# Generated by Django 6.0.6 on 2026-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_dealerprofile_friday_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='friday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='friday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='friday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='monday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='monday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='monday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='saturday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='saturday_closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='saturday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='sunday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='sunday_closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='sunday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='thursday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='thursday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='thursday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='tuesday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='tuesday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='tuesday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='wednesday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='wednesday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='wednesday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
