# Generated by Django 6.0.6 on 2026-06-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0024_dealerprofile_friday_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='business_slogan',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='dealer_owner_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='dealer_owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_owner_photos/'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='dealer_owner_title',
            field=models.CharField(blank=True, default='Dealer Principal', max_length=120),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='google_maps_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='years_in_business',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
