# Generated by Django 6.0.6 on 2026-07-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0028_dealerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('max_listings', models.PositiveIntegerField(default=3)),
                ('featured_ads_allowed', models.PositiveIntegerField(default=0)),
                ('is_featured_dealer', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='package',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
