# Generated by Django 6.0.6 on 2026-07-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0029_dealerpackage_alter_dealerprofile_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable or disable Stripe payments.')),
                ('test_mode', models.BooleanField(default=True, help_text='Turn off only when using live Stripe keys.')),
                ('publishable_key', models.CharField(blank=True, help_text='Stripe publishable key. Example: pk_test_... or pk_live_...', max_length=255)),
                ('secret_key', models.CharField(blank=True, help_text='Stripe secret key. Example: sk_test_... or sk_live_...', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Stripe webhook secret. Example: whsec_...', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stripe Settings',
                'verbose_name_plural': 'Stripe Settings',
            },
        ),
        migrations.RemoveField(
            model_name='dealerpackage',
            name='stripe_price_id',
        ),
    ]
