# Generated by Django 6.0.6 on 2026-07-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0031_car_admin_note_car_approved_at_car_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingListing',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Listing',
                'verbose_name_plural': 'Pending Listings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehicles.car',),
        ),
    ]
