# Generated by Django 6.0.6 on 2026-07-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0032_pendinglisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedListing',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Listing',
                'verbose_name_plural': '✅ Approved Listings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehicles.car',),
        ),
        migrations.CreateModel(
            name='RejectedListing',
            fields=[
            ],
            options={
                'verbose_name': 'Rejected Listing',
                'verbose_name_plural': '❌ Rejected Listings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehicles.car',),
        ),
        migrations.CreateModel(
            name='ReportedListing',
            fields=[
            ],
            options={
                'verbose_name': 'Reported Listing',
                'verbose_name_plural': '⚠️ Reported Listings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehicles.car',),
        ),
        migrations.CreateModel(
            name='SuspendedListing',
            fields=[
            ],
            options={
                'verbose_name': 'Suspended Listing',
                'verbose_name_plural': '🚫 Suspended Listings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehicles.car',),
        ),
        migrations.AlterModelOptions(
            name='pendinglisting',
            options={'verbose_name': 'Pending Listing', 'verbose_name_plural': '🚦 Pending Listings'},
        ),
    ]
