# Generated by Django 6.0.6 on 2026-07-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0033_approvedlisting_rejectedlisting_reportedlisting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendinglisting',
            options={'verbose_name': 'Pending Listing', 'verbose_name_plural': '★ Pending Listings'},
        ),
    ]
