# Generated by Django 6.0.6 on 2026-07-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0034_alter_pendinglisting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Dashboard',
                'verbose_name_plural': '★ Admin Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vehicles.car',),
        ),
    ]
