# Generated by Django 6.0.6 on 2026-07-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0035_moderationdashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationdashboard',
            options={'verbose_name': 'Global Moderation Center', 'verbose_name_plural': '★ Global Moderation Center'},
        ),
    ]
